spring:
  application:
    name: ContentCraft
  profiles:
    active: dev
  logging:
    level:
      org.springframework.boot.autoconfigure: WARN
      org.springframework.boot.actuate.autoconfigure: WARN
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: trend-collector-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  http:
    codecs:
      max-in-memory-size: 5MB

server:
  port: 9090

logging:
  level:
    com.yourcompany.trendcollector: INFO
    org.springframework.kafka: WARN

app:
  kafka:
    topics:
           raw-posts: raw-posts-topic-name
           trends: trends-topic-name
    processed-data: "processed-trend-data"

    twitter:
      api:
        key: "${TWITTER_API_KEY:your-twitter-api-key}"
  collection:
    interval: 60000 # 1 minute in milliseconds

